Escola/Models/Alunos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Escola.Models
{
    public partial class Alunos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        
        [DataType(DataType.Currency)]
        [Display(Name = "Valor da Mensalidade")]
        public decimal ValorMensalidade { get; set; }
        
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Data de Vencimento")]
        public DateTime DataVencimento { get; set; }

        public int idProfessor { get; set; }

    }
}

Escola/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Escola.Models;
using System.IO;
using System.Web;
using System.Text;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Configuration;

namespace Escola.Controllers
{
    public class AlunosController : Controller
    {
        private readonly EscolaContext _context;

        private readonly IConfiguration _configuration;

        public AlunosController(EscolaContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }


        public async Task<IActionResult> Index([FromQuery]string nome)
        {
            int id = 0;
            id = Convert.ToInt32(Request.RouteValues.Values.ElementAt(2));
            ViewBag.IdProfessor = id;
            ViewBag.NomeProfessor = nome;
            
            var alunos = await _context.Alunos.Where<Alunos>(p => p.idProfessor == id).ToListAsync();            
            return View(alunos);
        }

        public async Task<IActionResult> Importar()
        {
            string[] args = Request.RouteValues.Values.ElementAt(2).ToString().Split('?');

            var id = Convert.ToInt32(args[0]);
            var nome = args[1];

            if (Request.Form.Files.Count > 0)
            {

                DateTime ultimaAtualizacao;
                string data = _configuration.GetValue<string>("Bloqueio:LastUpdate");
                TimeSpan tempoBloqueio = TimeSpan.Parse(_configuration.GetValue<string>("Bloqueio:Time"));
                if (!String.IsNullOrEmpty(data))
                    ultimaAtualizacao = Convert.ToDateTime(data);
                else
                    ultimaAtualizacao = DateTime.Now;

               

                TimeSpan tempoDecorrido = DateTime.Now.Subtract(ultimaAtualizacao);

                if (tempoDecorrido < tempoBloqueio)
                {
                    ViewBag.Message = "Sistema bloqueado para importação";
                }
                else
                {
                    var file = Request.Form.Files[0];

                    if (file != null)
                    {
                        var result = new StringBuilder();
                        using (var reader = new StreamReader(file.OpenReadStream()))
                        {
                            while (reader.Peek() >= 0)
                            {
                                result.AppendLine(reader.ReadLine());

                                string[] dados = result.ToString().Split("||");

                                Alunos aluno = new Alunos();
                                aluno.Nome = dados[0];
                                aluno.ValorMensalidade = Convert.ToDecimal(dados[1]);
                                aluno.DataVencimento = Convert.ToDateTime(dados[2].Replace("\r\n", ""));
                                aluno.idProfessor = id;

                                _context.Add(aluno);
                                await _context.SaveChangesAsync();

                                result.Clear();
                            }
                        }

                    }
                    SetAppSettingValue("LastUpdate", DateTime.Now.ToString(), AppDomain.CurrentDomain.BaseDirectory);                    
                }               
            }
            else
            {
                ViewBag.Message = "Necessário selecionar um arquivo";
               
            }

            return RedirectToAction("Index", "Alunos", new { id = id, nome = nome });
            
        }
    
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var alunos =  _context.Alunos.Find(id);
            _context.Alunos.Remove(alunos);
            _context.SaveChanges();

            return NoContent();
        }

        public static void SetAppSettingValue(string key, string value, string appSettingsJsonFilePath = null)
        {
            if (appSettingsJsonFilePath == null)
            {
                appSettingsJsonFilePath = System.IO.Path.Combine(System.AppContext.BaseDirectory, "appsettings.json");
            }
            else
            {
                appSettingsJsonFilePath = System.IO.Path.Combine(appSettingsJsonFilePath, "appsettings.json");
            }

            var json = System.IO.File.ReadAllText(appSettingsJsonFilePath);
            dynamic jsonObj = Newtonsoft.Json.JsonConvert.DeserializeObject<Newtonsoft.Json.Linq.JObject>(json);


            jsonObj["Bloqueio"][key] = value;

            string output = Newtonsoft.Json.JsonConvert.SerializeObject(jsonObj, Newtonsoft.Json.Formatting.Indented);

            System.IO.File.WriteAllText(appSettingsJsonFilePath, output);
        }
    }
}

Escola/Controllers/ProfessoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Escola.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Escola.Controllers
{
    public class ProfessoresController : Controller
    {
        private readonly EscolaContext _context;

        public ProfessoresController(EscolaContext context)
        {
            _context = context;
        }

        // GET: Professores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Professores.ToListAsync());
        }
          
    
        public IActionResult ListarAlunos(int id, string nome)
        {            
            Professores professor = new Professores();
            professor.Id = id;
            professor.Nome = nome.TrimEnd();
            return RedirectToAction("Index", "Alunos", new { id = id, nome  = nome } );
        }

        // GET: Professores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professores = await _context.Professores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professores == null)
            {
                return NotFound();
            }

            return View(professores);
        }

        // GET: Professores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Professores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Professores professores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(professores);
        }

        // GET: Professores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professores = await _context.Professores.FindAsync(id);
            if (professores == null)
            {
                return NotFound();
            }
            return View(professores);
        }

        // POST: Professores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Professores professores)
        {
            if (id != professores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessoresExists(professores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professores);
        }

        // GET: Professores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professores = await _context.Professores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professores == null)
            {
                return NotFound();
            }

            return View(professores);
        }

        // POST: Professores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professores = await _context.Professores.FindAsync(id);
            _context.Professores.Remove(professores);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessoresExists(int id)
        {
            return _context.Professores.Any(e => e.Id == id);
        }
    }
}

Escola/Views/Alunos/Create.cshtml
@model Escola.Models.Alunos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorMensalidade" class="control-label"></label>
                <input asp-for="ValorMensalidade" class="form-control" />
                <span asp-validation-for="ValorMensalidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVencimento" class="control-label"></label>
                <input asp-for="DataVencimento" class="form-control" />
                <span asp-validation-for="DataVencimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Escola/Views/Alunos/Index.cshtml
@model IEnumerable<Escola.Models.Alunos>

@{
    ViewData["Title"] = "Index";
}

<script>
    function deleteItem(form) {
        $(form).parents('li').remove();
    }
</script>

<h1>Alunos</h1>
<script>
    function DeleteUsers(bID, el) {
        var result = confirm("Você deseja mesmo deletar este aluno ?");
        if (result) {
            userId = bID;
            jQuery.ajax
                ({
                    url: '/Alunos/Delete/' + userId,
                    type: 'POST',
                    dataType: 'json',
                    data: { str: userId },
                    success: function (data) {
                        var row = el.closest('tr');
                        row.remove();
                    },
                    error: function () {
                        var row = el.closest('tr');
                        row.remove();
                    }
                });
        }
    }
</script>

    <p>Alunos do Professor:  @ViewBag.NomeProfessor</p>
    <br />
    <form method="post" enctype="multipart/form-data" asp-route-id="@ViewBag.IdProfessor?@ViewBag.NomeProfessor"  asp-controller="Alunos" asp-action="Importar">
        <div class="form-group">
            <div class="col-md-10">
                <p>Importar alunos para este professor:</p>
                <input type="file" name="file" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Importar" />
            </div>
        </div>
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Message");
                };
            </script>

         }       
    </form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorMensalidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataVencimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorMensalidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVencimento)
                </td>
                <td>
                    <a id="btnDleteSingle" data-toggle="modal" data-target="#divDelete" onclick="DeleteUsers(@item.Id,this)">Excluir</a>

                </td>
            </tr>
        }
    </tbody>
</table>

<div>    
    @Html.ActionLink("Voltar", "Index", "Professores")
</div>